<script>
    const status={
        SUCCESS : "Successfully Executes",
        ERROR : "Internal Server Error"
    }
    function demo(){
        return new Promise((resolve,reject)=>{
            setTimeout(()=>{
                //resolve(status.SUCCESS);
                reject(status.ERROR);
            },2000);
        });
    }
    demo().then((msg)=>{
        console.log(msg);
    }).catch((error)=>{
        console.log("Error Occured");
    }).finally(()=>{
        console.log("Always Executes");
    });
</script>